CREATE DATABASE UTP_empleados;
-- Drop database utp_empleados;


USE UTP_empleados;

-- Modificar en un futuro para hacer foranea el codigo de cargo en lugar de nombre
-- De momento Empleados tiene 12 datos
CREATE TABLE Empleados(
CIP VARCHAR(20) NOT NULL,
Nombre VARCHAR(20),
Apellido VARCHAR(500),
Telefono VARCHAR(10),
Cargo_actual VARCHAR(200),
Sexo VARCHAR(1),
Fecha_nacimiento VARCHAR(10),
Formacion_academica VARCHAR(200),
Experiencia VARCHAR(100),
Referencias VARCHAR(200),
Centro_Regional VARCHAR(30),
Pruebas_psicotecnicas VARCHAR(200),

PRIMARY KEY (CIP)
-- FOREIGN KEY (Cargo_actual) REFERENCES Cargos(Nombre)
);

INSERT INTO Empleados VALUES ("8-333-3333","Maikol","Marin","63006000","Administrador de Soporte Tecnico","m","1998-07-20","Lic. Ing. de Sistemas y Computacion","2 anios - Administrador de Recursos Informaticos; 5 meses - Administrador de Soporte Tecnico","63000000 - Sra. Petronila","Panama Oeste","Administrador de Soporte Tecnico");

CREATE TABLE Cargos(
Codigo INT AUTO_INCREMENT NOT NULL ,
Nombre VARCHAR(200),
Familia VARCHAR(100),
Grupo_ocupacional VARCHAR(100),
Nivel_funcional VARCHAR(1000),
Grupo_laboral VARCHAR(10),
PDF  VARCHAR(1000),

PRIMARY KEY (Codigo)
);


-- ******************************************************************************************************
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ABOGADO","Servicios Legales, Seguridad Pública y Actividades Afines","Servicios Legales","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ABOGADO AUXILIAR","Servicios Legales, Seguridad Pública y Actividades Afines","Servicios Legales","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ADMINISTRADOR","Administración, Asistencia Técnica y Actividades Afines","Administración General","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ADMINISTRADOR DE ARCHIVO","Administración, Asistencia Técnica y Actividades Afines","Secretariado, Operación de Equipo de Oficina, Traducción y Actividades Afines","Apoyo, Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ADMINISTRADOR DE BASE DE DATOS","Administración, Asistencia Técnica y Actividades Afines","Procesamiento Electrónico de Datos","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ADMINISTRADOR DE HOWARD","Administración, Asistencia Técnica y Actividades Afines","Administración General","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ADMINISTRADOR DE LABORATORIO DE COMPUTO","Administración, Asistencia Técnica y Actividades Afines","Procesamiento Electrónico de Datos","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ADMINISTRADOR DE LIBRERÍA","Educación","Educación","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ADMINISTRADOR DE NIC-PANAMA","Administración, Asistencia Técnica y Actividades Afines","Procesamiento Electrónico de Datos","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ADMINISTRADOR DE PROYECTO","Administración, Asistencia Técnica y Actividades Afines","Administración General","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ADMINISTRADOR DE RECURSOS INFORMATICOS","Administración, Asistencia Técnica y Actividades Afines","Procesamiento Electrónico de Datos","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ADMINISTRADOR DE REDES","Administración, Asistencia Técnica y Actividades Afines","Procesamiento Electrónico de Datos","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ADMINISTRADOR DE SOPORTE TECNICO","Administración, Asistencia Técnica y Actividades Afines","Procesamiento Electrónico de Datos","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ADMINISTRADOR DE TOCUMEN","Administración, Asistencia Técnica y Actividades Afines","Administración General","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ADMINISTRADOR DEL CENTRO ESPECIALIZADO DE LENGUAS","Administración, Asistencia Técnica y Actividades Afines","Administración General","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ADMINISTRADOR DEL PROGRAMA DE AVIACION","Administración, Asistencia Técnica y Actividades Afines","Administración General","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ADMINISTRADOR WEB","Administración, Asistencia Técnica y Actividades Afines","Procesamiento Electrónico de Datos","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("AGENTE DE ATENCION AL PUBLICO","Administración, Asistencia Técnica y Actividades Afines","Secretariado, Operación de Equipo de Oficina, Traducción y Actividades Afines","Apoyo, Auxiliar y Asistencial","Auxiliar",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("AGENTE DE COMPRAS","Administración, Asistencia Técnica y Actividades Afines","Ventas, Compras y Almacenamiento","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("AGENTE DE MERCADEO","Administración, Asistencia Técnica y Actividades Afines","Estadística, Economía, Mercadeo, Turismo, Actuarial y Actividades Afines","Apoyo, Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("AGENTE DE SEGURIDAD","Servicios Legales, Seguridad Pública y Actividades Afines","Seguridad Pública","Apoyo, Auxiliar y Asistencial","Apoyo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ALBAÑIL","Mantenimiento, Construcción, Mecánica, Artesanía, Artes Gráficas y Oficios Diversos","Mantenimiento y Construcción","Apoyo, Auxiliar y Asistencial","Apoyo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ALMACENISTA","Administración, Asistencia Técnica y Actividades Afines","Ventas, Compras y Almacenamiento","Apoyo, Auxiliar y Asistencial","Apoyo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ANALISTA DE BIENESTAR SOCIAL Y RELACIONES LABORALES","Trabajo, Bienestar Social y Actividades Afines","Bienestar Social y Afines","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ANALISTA DE CREDITOS ACADEMICOS","Educación","Formación Profesional y Aprovechamiento de Recursos Humanos","Apoyo, Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ANALISTA DE PRESUPUESTO","Administración, Asistencia Técnica y Actividades Afines","Planificación, Análisis Administrativo, Personal y Presupuesto","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ANALISTA DE RECURSO HUMANO","Administración, Asistencia Técnica y Actividades Afines","Planificación, Análisis Administrativo, Personal y Presupuesto","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ANALISTA DE REGISTROS DOCENTES","Administración, Asistencia Técnica y Actividades Afines","Planificación, Análisis Administrativo, Personal y Presupuesto","Apoyo, Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ANALISTA DE SALUD, SEGURIDAD E HIGIENE DEL TRABAJO","Trabajo, Bienestar Social y Actividades Afines","Bienestar Social y Afines","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ANALISTA DE SISTEMAS","Administración, Asistencia Técnica y Actividades Afines","Procesamiento Electrónico de Datos","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ANALISTA PROGRAMADOR","Administración, Asistencia Técnica y Actividades Afines","Procesamiento Electrónico de Datos","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ANALISTA DE SEGUROS","Administración, Asistencia Técnica y Actividades Afines","Administración General","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ARCHIVERO","Administración, Asistencia Técnica y Actividades Afines","Secretariado, Operación de Equipo de Oficina, Traducción y Actividades Afines","Apoyo, Auxiliar y Asistencial","Auxiliar",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ARCHIVISTA DIGITAL","Administración, Asistencia Técnica y Actividades Afines","Secretariado, Operación de Equipo de Oficina, Traducción y Actividades Afines","Apoyo, Auxiliar y Asistencial","Auxiliar",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ARQUITECTO","Arquitectura, Ingeniería, Geodesia, Geografía y Actividades Afines","Arquitectura","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ARQUITECTO SENIOR","Arquitectura, Ingeniería, Geodesia, Geografía y Actividades Afines","Arquitectura","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ASISTENTE ADMINISTRATIVO","Administración, Asistencia Técnica y Actividades Afines","Administración General","Apoyo, Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ASISTENTE DE ABOGADO","Servicios Legales, Seguridad Pública y Actividades Afines","Servicios Legales","Apoyo, Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ASISTENTE DE ANALISTA DE BIENESTAR SOCIAL","Trabajo, Bienestar Social y Actividades Afines","Bienestar Social y Afines","Apoyo, Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ASISTENTE DE ARQUITECTO","Arquitectura, Ingeniería, Geodesia, Geografía y Actividades Afines","Arquitectura","Apoyo, Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ASISTENTE DE BIBLIOTECOLOGO","Educación","Bibliotecología y Actividades Afines","Apoyo, Auxiliar y Asistencial","Auxiliar",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ASISTENTE DE CAPACITACION","Administración, Asistencia Técnica y Actividades Afines","Planificación, Análisis Administrativo, Personal y Presupuesto","Apoyo, Auxiliar y Asistencial","Auxiliar",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ASISTENTE DE CONTABILIDAD","Administración, Asistencia Técnica y Actividades Afines","Contabilidad, Auditoria, Banca, Finanzas y Actividades Afines","Apoyo, Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ASISTENTE DE INFORMACIÓN Y CONTROL ESTUDIANTIL","Administración, Asistencia Técnica y Actividades Afines","Información, Divulgación y Relaciones Públicas","Apoyo, Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ASISTENTE DE LABORATORIO","Mantenimiento, Construcción, Mecánica, Artesanía, Artes Gráficas y Oficios Diversos","Oficios Diversos","Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ASISTENTE DE LABORATORIO DE INFORMATICA","Administración, Asistencia Técnica y Actividades Afines","Procesamiento Electrónico de Datos","Apoyo, Auxiliar y Asistencial","Auxiliar",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ASISTENTE DE LABORATORIO DE SANITARIA","Arquitectura, Ingeniería, Geodesia, Geografía y Actividades Afines","Ingeniería Sanitaria y Afines","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ASISTENTE DE OFICIAL DE PERSONAL","Administración, Asistencia Técnica y Actividades Afines","Planificación, Análisis Administrativo, Personal y Presupuesto","Apoyo, Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ASISTENTE DE OFICIAL DE PLANILLAS","Administración, Asistencia Técnica y Actividades Afines","Contabilidad, Auditoria, Banca, Finanzas y Actividades Afines","Apoyo, Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ASISTENTE DE OFICIAL DE PROTOCOLO","Administración, Asistencia Técnica y Actividades Afines","Información, Divulgación y Relaciones Públicas","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ASISTENTE DE PRODUCTOR","Administración, Asistencia Técnica y Actividades Afines","Información, Divulgación y Relaciones Públicas","Apoyo, Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ASISTENTE DE RECURSOS DE APOYO INFORMATICO","Administración, Asistencia Técnica y Actividades Afines","Procesamiento Electrónico de Datos","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ASISTENTE DE RECURSOS HUMANOS","Administración, Asistencia Técnica y Actividades Afines","Planificación, Análisis Administrativo, Personal y Presupuesto","Apoyo, Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ASISTENTE DE TECNICO AGRICOLA","Ciencias Agropecuarias, Naturales y Actividades Afines","Ciencias Agropecuarias","Apoyo, Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ASISTENTE DE TRABAJADOR SOCIAL","Trabajo, Bienestar Social y Actividades Afines","Bienestar Social y Afines","Apoyo, Auxiliar y Asistencial","Auxiliar",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ASISTENTE EJECUTIVO","Administración, Asistencia Técnica y Actividades Afines","Administración General","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ASISTENTE EJECUTIVO DEL RECTOR","Administración, Asistencia Técnica y Actividades Afines","Administración General","Ejecutivo","Directivo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ASISTENTE MEDICO","Salud Pública y Actividades Afines","Enfermería y Afines","Apoyo, Auxiliar y Asistencial","Apoyo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ASISTENTE TECNICO","Administración, Asistencia Técnica y Actividades Afines","Administración General","Apoyo, Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ASISTENTE TECNICO DE PROYECTOS","Administración, Asistencia Técnica y Actividades Afines","Administración General","Apoyo, Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("AUDITOR","Administración, Asistencia Técnica y Actividades Afines","Contabilidad, Auditoria, Banca, Finanzas y Actividades Afines","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("AUXILIAR DE ARCHIVO","Administración, Asistencia Técnica y Actividades Afines","Secretariado, Operación de Equipo de Oficina, Traducción y Actividades Afines","Apoyo, Auxiliar y Asistencial","Apoyo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("AUXILIAR DE BIBLIOTECA","Educación","Bibliotecología y Actividades Afines","Apoyo, Auxiliar y Asistencial","Apoyo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("AUXILIAR DE COCINA","Salud Pública y Actividades Afines","Nutrición, Dietética y Servicio de Alimentos","Apoyo, Auxiliar y Asistencial","Apoyo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("AUXILIAR DE LABORATORIO","Mantenimiento, Construcción, Mecánica, Artesanía, Artes Gráficas y Oficios Diversos","Oficios Diversos","Apoyo, Auxiliar y Asistencial","Apoyo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("AUXILIAR DE OFICIAL DE PROTOCOLO","Administración, Asistencia Técnica y Actividades Afines","Información, Divulgación y Relaciones Públicas","Apoyo, Auxiliar y Asistencial","Apoyo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("AUXILIAR DE ORGANIZACIÓN DE EVENTOS","Administración, Asistencia Técnica y Actividades Afines","Información, Divulgación y Relaciones Públicas","Apoyo, Auxiliar y Asistencial","Apoyo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("AYUDANTE ACADÉMICO ESTUDIANTIL","Educación","Actividades Universitarias","Apoyo, Auxiliar y Asistencial","Apoyo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("AYUDANTE ADMINISTRATIVO ESTUDIANTIL","Educación","Actividades Universitarias","Apoyo, Auxiliar y Asistencial","Apoyo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("AYUDANTE DE ALBAÑIL","Mantenimiento, Construcción, Mecánica, Artesanía, Artes Gráficas y Oficios Diversos","Mantenimiento y Construcción","Apoyo, Auxiliar y Asistencial","Apoyo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("AYUDANTE DE ALMACENISTA","Administración, Asistencia Técnica y Actividades Afines","Ventas, Compras y Almacenamiento","Apoyo, Auxiliar y Asistencial","Apoyo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("AYUDANTE DE CHAPISTERO","Mantenimiento, Construcción, Mecánica, Artesanía, Artes Gráficas y Oficios Diversos","Mecánico Automotriz, de Aviación, Operación de Equipo Pesado y Actividades Afines","Apoyo, Auxiliar y Asistencial","Apoyo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("AYUDANTE DE FONTANERO","Mantenimiento, Construcción, Mecánica, Artesanía, Artes Gráficas y Oficios Diversos","Mantenimiento y Construcción","Apoyo, Auxiliar y Asistencial","Apoyo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("AYUDANTE DE INVESTIGACIÓN ESTUDIANTIL","Educación","Actividades Universitarias","Apoyo, Auxiliar y Asistencial","Apoyo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("AYUDANTE DE MECANICA","Mantenimiento, Construcción, Mecánica, Artesanía, Artes Gráficas y Oficios Diversos","Mecánica en General","Apoyo, Auxiliar y Asistencial","Apoyo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("AYUDANTE DE MECANICO DE REFRIGERACION","Mantenimiento, Construcción, Mecánica, Artesanía, Artes Gráficas y Oficios Diversos","Mecánica en General","Apoyo, Auxiliar y Asistencial","Apoyo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("AYUDANTE GENERAL","Mantenimiento, Construcción, Mecánica, Artesanía, Artes Gráficas y Oficios Diversos","Mantenimiento y Construcción","Apoyo, Auxiliar y Asistencial","Apoyo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("AYUDANTE TECNICO","Administración, Asistencia Técnica y Actividades Afines","Administración General","Apoyo, Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("BIBLIOTECOLOGO","Educación","Bibliotecología y Actividades Afines","Apoyo, Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("BIOLOGO","Ciencias Agropecuarias, Naturales y Actividades Afines","Ciencias Naturales","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("CAJERO","Administración, Asistencia Técnica y Actividades Afines","Tributación, Fiscalización y Control de Fondos Públicos","Apoyo, Auxiliar y Asistencial","Auxiliar",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("CAJERO DE CAFETERIA","Administración, Asistencia Técnica y Actividades Afines","Tributación, Fiscalización y Control de Fondos Públicos","Apoyo, Auxiliar y Asistencia","Apoyo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("CAMARÓGRAFO","Administración, Asistencia Técnica y Actividades Afines","Información, Divulgación y Relaciones Públicas","Apoyo, Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("CARPINTERO","Mantenimiento, Construcción, Mecánica, Artesanía, Artes Gráficas y Oficios Diversos","Mantenimiento y Construcción","Apoyo, Auxiliar y Asistencial","Apoyo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("CHAPISTERO","Mantenimiento, Construcción, Mecánica, Artesanía, Artes Gráficas y Oficios Diversos","Mecánico Automotriz, de Aviación, Operación de Equipo Pesado y Actividades Afines","Apoyo, Auxiliar y Asistencial","Apoyo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("COCINERO","Salud Pública y Actividades Afines","Nutrición, Dietética y Servicio de Alimentos","Apoyo, Auxiliar y Asistencial","Auxiliar",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("COCINERO JEFE","Salud Pública y Actividades Afines","Nutrición, Dietética y Servicio de Alimentos","Apoyo, Auxiliar y Asistencial","Auxiliar",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("COMUNICADOR PEDAGOGICO","Educación","Educación","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("CONDUCTOR DE VEHICULO","Telecomunicaciones, Correos, Transporte y Actividades Afines","Transporte y Actividades Afines","Apoyo, Auxiliar y Asistencial","Apoyo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("CONDUCTOR DE VEHICULO DE EJECUTIVO","Telecomunicaciones, Correos, Transporte y Actividades Afines","Transporte y Actividades Afines","Apoyo, Auxiliar y Asistencial","Auxiliar",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("CONDUCTOR DE VEHICULO PESADO","Telecomunicaciones, Correos, Transporte y Actividades Afines","Transporte y Actividades Afines","Apoyo, Auxiliar y Asistencial","Auxiliar",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("CONSERJE","Mantenimiento, Construcción, Mecánica, Artesanía, Artes Gráficas y Oficios Diversos","Mantenimiento y Construcción","Apoyo, Auxiliar y Asistencial","Apoyo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("CONTADOR","Administración, Asistencia Técnica y Actividades Afines","Contabilidad, Auditoria, Banca, Finanzas y Actividades Afines","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("COORDINADOR ADMINISTRATIVO DE CENTRO DE INVESTIGACION","Educación","Formación Profesional y Aprovechamiento de Recursos Humanos","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("COORDINADOR ARTISTICO","Educación","Bellas Artes, Cultura y Actividades Afines","Apoyo, Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("COORDINADOR DE ACTIVIDADES DEPORTIVAS","Educación","Deportes","Apoyo, Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("COORDINADOR DE ACTIVIDADES DEPORTIVAS Y CULTURALES","Educación","Deportes","Apoyo, Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("COORDINADOR DE ACTIVIDADES FOLKLORICAS","Educación","Bellas Artes, Cultura y Actividades Afines","Apoyo, Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("COORDINADOR DE ACTIVIDADES RECREATIVAS Y CULTURALES","Educación","Bellas Artes, Cultura y Actividades Afines","Apoyo, Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("COORDINADOR DE BANDA MUSICAL","Educación","Bellas Artes, Cultura y Actividades Afines","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("COORDINADOR DE COOPERACION INTERNACIONAL","Administración, Asistencia Técnica y Actividades Afines","Información, Divulgación y Relaciones Públicas","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("COORDINADOR DE DIFUSION CULTURAL","Educación","Bellas Artes, Cultura y Actividades Afines","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("COORDINADOR DE MANTENIMIENTO DE CENTRO REGIONAL","Mantenimiento, Construcción, Mecánica, Artesanía, Artes Gráficas y Oficios Diversos","Mantenimiento y Construcción","Apoyo, Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("COORDINADOR DE MOVILIDAD","Administración, Asistencia Técnica y Actividades Afines","Información, Divulgación y Relaciones Públicas","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("COORDINADOR DE OFICINA DE METAS","Administración, Asistencia Técnica y Actividades Afines","Asesoría, Consultoría, Programas Especiales y Actividades Afines","Técnico y Profesional","Jefes de Departamento",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("COORDINADOR DE PROYECTO","Administración, Asistencia Técnica y Actividades Afines","Administración General","Técnico y Profesional","Jefes de Departamento",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("COORDINADOR DEL SISTEMA DE INGRESO UNIVERSITARIO","Administración, Asistencia Técnica y Actividades Afines","Estadística, Economía, Mercadeo, Turismo, Actuarial y Actividades Afines","Apoyo, Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("COORDINADOR DE TEATRO","Educación","Bellas Artes, Cultura y Actividades Afines","Apoyo, Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("COREOGRAFO","Educación","Bellas Artes, Cultura y Actividades Afines","Apoyo, Auxiliar y Asistencial","Apoyo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("DIBUJANTE","Arquitectura, Ingeniería, Geodesia, Geografía y Actividades Afines","Arquitectura","Apoyo, Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("DIBUJANTE CALCULISTA","Arquitectura, Ingeniería, Geodesia, Geografía y Actividades Afines","Arquitectura","Apoyo, Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("DIRECTOR ADMINISTRATIVO","Administración, Asistencia Técnica y Actividades Afines","Administración General","Ejecutivo","Directivo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("DIRECTOR DE ASESORÍA LEGAL","Administración, Asistencia Técnica y Actividades Afines","Asesoría, Consultoría, Programas Especiales y Actividades Afines","Ejecutivo","Directivo",""); 

-- ******************************************************************************************************
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("DIRECTOR DE AUDITORIA INTERNA Y TRANSPARENCIA","Administración, Asistencia Técnica y Actividades Afines","Contabilidad, Auditoria, Banca, Finanzas y Actividades Afines","Ejecutivo","Directivo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("DIRECTOR DE BIBLIOTECA","Educación","Bibliotecología y Actividades Afines","Técnico y Profesional","Jefes de Departamento",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("DIRECTOR DE BIENESTAR ESTUDIANTIL","Educación","Formación Profesional y Aprovechamiento de Recursos Humanos","Técnico y Profesional","Jefes de Departamento",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("DIRECTOR DE CENTRO DE DISTRIBUCIÓN Y LIBRERÍAS","Administración, Asistencia Técnica y Actividades Afines","Información, Divulgación y Relaciones Públicas","Técnico y Profesional","Jefes de Departamento",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("DIRECTOR DE COMUNICACION ESTRATEGICA","Mantenimiento, Construcción, Mecánica, Artesanía, Artes Gráficas y Oficios Diversos","Artes Gráficas","Técnico y Profesional","Jefes de Departamento",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("DIRECTOR DE CULTURA Y DEPORTES","Educación","Bellas Artes, Cultura y Actividades Afines","Técnico y Profesional","Jefes de Departamento",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("DIRECTOR DE EDITORIAL UNIVERSITARIA","Educación","Educación","Técnico y Profesional","Jefes de Departamento",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("DIRECTOR DE FINANZAS","Administración, Asistencia Técnica y Actividades Afines","Contabilidad, Auditoria, Banca, Finanzas y Actividades Afines","Ejecutivo","Directivo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("DIRECTOR DE INCLUSION E INTEGRACION UNIVERSITARIA","Trabajo, Bienestar Social y Actividades Afines","Bienestar Social y Afines","Técnico y Profesional","Jefes de Departamento",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("DIRECTOR DE LABORATORIO DE LENGUAS","Administración, Asistencia Técnica y Actividades Afines","Administración General","Ejecutivo","Directivo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("DIRECTOR DE ORIENTACION PSICOLOGICA","Salud Pública y Actividades Afines","Medicina, Odontología y Afines","Técnico y Profesional","Jefes de Departamento",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("DIRECTOR DE PLANIFICACION UNIVERSITARIA","Administración, Asistencia Técnica y Actividades Afines","Planificación, Análisis Administrativo, Personal y Presupuesto","Ejecutivo","Directivo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("DIRECTOR DE PRESUPUESTO","Administración, Asistencia Técnica y Actividades Afines","Planificación, Análisis Administrativo, Personal y Presupuesto","Ejecutivo","Directivo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("DIRECTOR DE PROTOCOLO CEREMONIAL Y ORGANIZACION DE EVENTOS","Administración, Asistencia Técnica y Actividades Afines","Información, Divulgación y Relaciones Públicas","Técnico y Profesional","Jefes de Departamento",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("DIRECTOR DE PROVEEDURIA Y COMPRAS","Administración, Asistencia Técnica y Actividades Afines","Ventas, Compras y Almacenamiento","Ejecutivo","Directivo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("DIRECTOR DE RELACIONES INTERNACIONALES","Administración, Asistencia Técnica y Actividades Afines","Información, Divulgación y Relaciones Públicas","Ejecutivo","Directivo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("DIRECTOR DE SECRETARIA DE VIDA UNIVERSITARIA","Educación","Actividades Universitarias","Ejecutivo","Directivo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("DIRECTOR DEL SISTEMA DE INGRESO UNIVERSITARIO","Administración, Asistencia Técnica y Actividades Afines","Información, Divulgación y Relaciones Públicas","Técnico y Profesional","Jefes de Departamento",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("DIRECTOR DE TECNOLOGIA DE LA INFORMACION Y COMUNICACION","Administración, Asistencia Técnica y Actividades Afines","Procesamiento Electrónico de Datos","Ejecutivo","Directivo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("DIRECTOR DEL SERVICIO SOCIAL UNIVERSITARIO","Educación","Actividades Universitarias","Técnico y Profesional","Jefes de Departamento",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("DIRECTOR GENERAL DE INGENIERIA Y ARQUITECTURA","Arquitectura, Ingeniería, Geodesia, Geografía y Actividades Afines","Ingeniería Civil y Afines","Ejecutivo","Directivo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("DIRECTOR GENERAL DE RECURSOS HUMANOS","Administración, Asistencia Técnica y Actividades Afines","Planificación, Análisis Administrativo, Personal y Presupuesto","Ejecutivo","Directivo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("DISEÑADOR GRAFICO","Mantenimiento, Construcción, Mecánica, Artesanía, Artes Gráficas y Oficios Diversos","Artes Gráficas","Apoyo, Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("DISEÑADOR MULTIMEDIA","Administración, Asistencia Técnica y Actividades Afines","Procesamiento Electrónico de Datos","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("DISEÑADOR VISUAL","Mantenimiento, Construcción, Mecánica, Artesanía, Artes Gráficas y Oficios Diversos","Artes Gráficas","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("DISEÑADOR WEB","Administración, Asistencia Técnica y Actividades Afines","Procesamiento Electrónico de Datos","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("EBANISTA","Mantenimiento, Construcción, Mecánica, Artesanía, Artes Gráficas y Oficios Diversos","Artesanía en General","Apoyo, Auxiliar y Asistencial","Apoyo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("EDITOR AUDIOVISUAL","Administración, Asistencia Técnica y Actividades Afines","Información, Divulgación y Relaciones Públicas","Apoyo, Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ELECTRICISTA","Mantenimiento, Construcción, Mecánica, Artesanía, Artes Gráficas y Oficios Diversos","Mantenimiento y Construcción","Apoyo, Auxiliar y Asistencial","Auxiliar",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ENCUADERNADOR","Mantenimiento, Construcción, Mecánica, Artesanía, Artes Gráficas y Oficios Diversos","Artes Gráficas","Apoyo, Auxiliar y Asistencial","Apoyo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ENFERMERO","Salud Pública y Actividades Afines","Medicina, Odontología y Afines","Apoyo, Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ENTRENADOR DEPORTIVO","Educación","Deportes","Apoyo, Auxiliar y Asistencial","Auxiliar",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ESCENÓGRAFO","Administración, Asistencia Técnica y Actividades Afines","Información, Divulgación y Relaciones Públicas","Apoyo, Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("ESTADISTICO","Administración, Asistencia Técnica y Actividades Afines","Estadística, Economía, Mercadeo, Turismo, Actuarial y Actividades Afines","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("FORMULADOR DE PROYECTO","Administración, Asistencia Técnica y Actividades Afines","Administración General","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("EVALUADOR PRESUPUESTARIO","Administración, Asistencia Técnica y Actividades Afines","Planificación, Análisis Administrativo, Personal y Presupuesto","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("FONTANERO","Mantenimiento, Construcción, Mecánica, Artesanía, Artes Gráficas y Oficios Diversos","Mantenimiento y Construcción","Apoyo, Auxiliar y Asistencial","Apoyo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("FORMULADOR DE PROYECTO","Administración, Asistencia Técnica y Actividades Afines","Administración General","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("FOTOGRAFO","Administración, Asistencia Técnica y Actividades Afines","Información, Divulgación y Relaciones Públicas","Apoyo, Auxiliar y Asistencial","Auxiliar",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("GEOGRAFO","Arquitectura, Ingeniería, Geodesia, Geografía y Actividades Afines","Geodesia y Geografía","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("INGENIERO AGROQUIMICO","Ciencias Agropecuarias, Naturales y Actividades Afines","Ciencias Agropecuarias","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("INGENIERO AMBIENTAL","Arquitectura, Ingeniería, Geodesia, Geografía y Actividades Afines","Ingeniería Sanitaria y Afines","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("INGENIERO CIVIL","Arquitectura, Ingeniería, Geodesia, Geografía y Actividades Afines","Ingeniería Civil y Afines","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("INGENIERO DE SISTEMAS COMPUTACIONALES","Administración, Asistencia Técnica y Actividades Afines","Procesamiento Electrónico de Datos","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("INGENIERO ELECTRICO","Arquitectura, Ingeniería, Geodesia, Geografía y Actividades Afines","Ingeniería Eléctrica y Electromecánica","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("INGENIERO ELECTRICO-ELECTRONICO","Arquitectura, Ingeniería, Geodesia, Geografía y Actividades Afines","Ingeniería Eléctrica y Electromecánica","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("INGENIERO ELECTROMECANICO","Arquitectura, Ingeniería, Geodesia, Geografía y Actividades Afines","Ingeniería Eléctrica y Electromecánica","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("INGENIERO EN ELECTRONICA Y TELECOMUNICACIONES","Arquitectura, Ingeniería, Geodesia, Geografía y Actividades Afines","Ingeniería Eléctrica y Electromecánica","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("INGENIERO GEOMÁTICO","Arquitectura, Ingeniería, Geodesia, Geografía y Actividades Afines","Geodesia y Geografía","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("INGENIERO INDUSTRIAL","Arquitectura, Ingeniería, Geodesia, Geografía y Actividades Afines","Ingeniería Industrial, Química y de Minas","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("INGENIERO MECANICO","Mantenimiento, Construcción, Mecánica, Artesanía, Artes Gráficas y Oficios Diversos","Mecánica en General","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("INGENIERO MECANICO INDUSTRIAL","Arquitectura, Ingeniería, Geodesia, Geografía y Actividades Afines","Ingeniería Industrial, Química y de Minas","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("INSTRUCTOR DE CAPACITACION","Educación","Educación","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JARDINERO","Mantenimiento, Construcción, Mecánica, Artesanía, Artes Gráficas y Oficios Diversos","Oficios Diversos","Apoyo, Auxiliar y Asistencial","Apoyo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE DEPARTAMENTO DE CAPACITACIÓN CONTINUA EN TIC'S","Administración, Asistencia Técnica y Actividades Afines","Procesamiento Electrónico de Datos","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE DEPARTAMENTO DE ALMACEN","Administración, Asistencia Técnica y Actividades Afines","Ventas, Compras y Almacenamiento","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE DEPARTAMENTO DE ARCHIVOS GENERALES","Administración, Asistencia Técnica y Actividades Afines","Información, Divulgación y Relaciones Públicas","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE DEPARTAMENTO DE AUDITORIA INTERNA","Administración, Asistencia Técnica y Actividades Afines","Contabilidad, Auditoria, Banca, Finanzas y Actividades Afines","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE DEPARTAMENTO DE BIENES PATRIMONIALES","Administración, Asistencia Técnica y Actividades Afines","Contabilidad, Auditoria, Banca, Finanzas y Actividades Afines","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE DEPARTAMENTO DE BIENESTAR Y RELACIONES LABORALES","Administración, Asistencia Técnica y Actividades Afines","Estadística, Economía, Mercadeo, Turismo, Actuarial y Actividades Afines","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE DEPARTAMENTO DE CAFETERIA","Salud Pública y Actividades Afines","Nutrición, Dietética y Servicio de Alimentos","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE DEPARTAMENTO DE CAPACITACION Y DESARROLLO","Administración, Asistencia Técnica y Actividades Afines","Planificación, Análisis Administrativo, Personal y Presupuesto","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE DEPARTAMENTO DE COMPRAS MENORES, SEGUIMIENTO Y CONTR","Administración, Asistencia Técnica y Actividades Afines","Ventas, Compras y Almacenamiento","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE DEPARTAMENTO DE COMUNICACION E IMAGEN","Administración, Asistencia Técnica y Actividades Afines","Información, Divulgación y Relaciones Públicas","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE DEPARTAMENTO DE COMUNICACIÓN GRÁFICA","Administración, Asistencia Técnica y Actividades Afines","Información, Divulgación y Relaciones Públicas","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE DEPARTAMENTO DE CONSULTORÍA JURÍDICA Y TRÁMITES ADM.","Servicios Legales, Seguridad Pública y Actividades Afines","Servicios Legales","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE DEPARTAMENTO DE CONTABILIDAD","Administración, Asistencia Técnica y Actividades Afines","Contabilidad, Auditoria, Banca, Finanzas y Actividades Afines","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE DEPARTAMENTO DE CONTRATOS, CONVENIOS Y OTROS","Servicios Legales, Seguridad Pública y Actividades Afines","Servicios Legales","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE DEPARTAMENTO DE CULTURA","Educación","Bellas Artes, Cultura y Actividades Afines","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE DEPARTAMENTO DE DEPORTES","Educación","Deportes","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE DEPARTAMENTO DE DESARROLLO DE SIST. DE INFORMACIÓN","Administración, Asistencia Técnica y Actividades Afines","Procesamiento Electrónico de Datos","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE DEPARTAMENTO DE DISEÑO Y DESARROLLO DE PROYECTOS","Mantenimiento, Construcción, Mecánica, Artesanía, Artes Gráficas y Oficios Diversos","Mantenimiento y Construcción","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE DEPARTAMENTO DE ESTADISTICA E INDICADORES","Administración, Asistencia Técnica y Actividades Afines","Estadística, Economía, Mercadeo, Turismo, Actuarial y Actividades Afines","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE DEPARTAMENTO DE EVALUACIÓN DEL DESEMPEÑO E INCENTIVO","Administración, Asistencia Técnica y Actividades Afines","Planificación, Análisis Administrativo, Personal y Presupuesto","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE DEPARTAMENTO DE EVALUACION Y CALIDAD","Administración, Asistencia Técnica y Actividades Afines","Planificación, Análisis Administrativo, Personal y Presupuesto","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE DEPARTAMENTO DE INFORMACIÓN Y CONTROL ADMINISTRATIVO","Administración, Asistencia Técnica y Actividades Afines","Planificación, Análisis Administrativo, Personal y Presupuesto","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE DEPARTAMENTO DE JURISDICCIÓN ORDINARIA Y ADM.","Servicios Legales, Seguridad Pública y Actividades Afines","Servicios Legales","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE DEPARTAMENTO DE LICITACIONES","Administración, Asistencia Técnica y Actividades Afines","Ventas, Compras y Almacenamiento","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE DEPARTAMENTO DE PLANIFICACION Y ADM. DE REC. HUMANOS","Administración, Asistencia Técnica y Actividades Afines","Planificación, Análisis Administrativo, Personal y Presupuesto","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE DEPARTAMENTO DE PLANIFICACION Y PROYECTOS ESPECIALES","Administración, Asistencia Técnica y Actividades Afines","Planificación, Análisis Administrativo, Personal y Presupuesto","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE DEPARTAMENTO DE PLANILLAS Y DESCUENTOS","Administración, Asistencia Técnica y Actividades Afines","Contabilidad, Auditoria, Banca, Finanzas y Actividades Afines","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE DEPARTAMENTO DE PROGRAM. Y EVALUACIÓN PRESUPUESTARIA","Administración, Asistencia Técnica y Actividades Afines","Planificación, Análisis Administrativo, Personal y Presupuesto","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE DEPARTAMENTO DE PROGRAMACION PRESUPUESTARIA Y DESARR","Administración, Asistencia Técnica y Actividades Afines","Planificación, Análisis Administrativo, Personal y Presupuesto","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE DEPARTAMENTO DE REDES Y TELECOMUNICACIONES","Administración, Asistencia Técnica y Actividades Afines","Procesamiento Electrónico de Datos","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE DEPARTAMENTO DE REGISTROS E HISTORIAL ACADEMICOS","Educación","Formación Profesional y Aprovechamiento de Recursos Humanos","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE DEPARTAMENTO DE SEGURIDAD INSTITUCIONAL","Servicios Legales, Seguridad Pública y Actividades Afines","Seguridad Pública","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE DEPARTAMENTO DE SERVICIO AL PÚBLICO","Administración, Asistencia Técnica y Actividades Afines","Información, Divulgación y Relaciones Públicas","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE DEPARTAMENTO DE SERVICIOS ADM. GENERALES","Mantenimiento, Construcción, Mecánica, Artesanía, Artes Gráficas y Oficios Diversos","Mantenimiento y Construcción","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE DEPARTAMENTO DE SOPORTE TECNICO","Administración, Asistencia Técnica y Actividades Afines","Procesamiento Electrónico de Datos","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE DEPARTAMENTO DE TECNOLOGÍA WEB Y MULTIMEDIA","Administración, Asistencia Técnica y Actividades Afines","Procesamiento Electrónico de Datos","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE DEPARTAMENTO DE TESORERIA","Administración, Asistencia Técnica y Actividades Afines","Tributación, Fiscalización y Control de Fondos Públicos","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE DEPARTAMENTO DE TRANSPORTE","Telecomunicaciones, Correos, Transporte y Actividades Afines","Transporte y Actividades Afines","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE LABORATORIO DE ANALISIS IND. Y CIENCIAS AMBIENTALES","Arquitectura, Ingeniería, Geodesia, Geografía y Actividades Afines","Ingeniería Industrial, Química y de Minas","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE LABORATORIO DE SUELOS","Arquitectura, Ingeniería, Geodesia, Geografía y Actividades Afines","Ingeniería Civil y Afines","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE SECCIÓN DE ABASTECIMIENTO Y ALMACEN","Administración, Asistencia Técnica y Actividades Afines","Ventas, Compras y Almacenamiento","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE SECCION DE ACCIONES DE PERSONAL","Administración, Asistencia Técnica y Actividades Afines","Planificación, Análisis Administrativo, Personal y Presupuesto","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE SECCIÓN DE ALMACEN DE EQUIP., HERRAM. Y MAT. DE CONS","Administración, Asistencia Técnica y Actividades Afines","Ventas, Compras y Almacenamiento","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE SECCIÓN DE ALMACEN DE MAT. Y SUMINISTROS DE OFICINA","Administración, Asistencia Técnica y Actividades Afines","Ventas, Compras y Almacenamiento","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE SECCION DE ANAL. Y PREPARACION DE INFOR. FINANCIERA","Administración, Asistencia Técnica y Actividades Afines","Contabilidad, Auditoria, Banca, Finanzas y Actividades Afines","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE SECCIÓN DE ARCHIVOS ACADÉMICOS Y DE INVESTIGACIÓN","Administración, Asistencia Técnica y Actividades Afines","Información, Divulgación y Relaciones Públicas","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE SECCIÓN DE ARCHIVOS ADMINISTRATIVOS","Administración, Asistencia Técnica y Actividades Afines","Información, Divulgación y Relaciones Públicas","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE SECCIÓN DE ÁREAS VERDES","Mantenimiento, Construcción, Mecánica, Artesanía, Artes Gráficas y Oficios Diversos","Oficios Diversos","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE SECCION DE ASISTENCIA","Administración, Asistencia Técnica y Actividades Afines","Planificación, Análisis Administrativo, Personal y Presupuesto","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE SECCIÓN DE ATENCIÓN DE ACTOS PÚBLICOS","Administración, Asistencia Técnica y Actividades Afines","Información, Divulgación y Relaciones Públicas","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE SECCIÓN DE ATENCIÓN DE EVENTOS","Administración, Asistencia Técnica y Actividades Afines","Información, Divulgación y Relaciones Públicas","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE SECCIÓN DE COCINA","Salud Pública y Actividades Afines","Nutrición, Dietética y Servicio de Alimentos","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE SECCIÓN DE COMPRAS MENORES","Administración, Asistencia Técnica y Actividades Afines","Ventas, Compras y Almacenamiento","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE SECCIÓN DE CONFEC. DE PLIEGO DE CARG. Y ASES. TÉCN.","Administración, Asistencia Técnica y Actividades Afines","Ventas, Compras y Almacenamiento","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE SECCIÓN DE EDUCACIÓN Y CAPACITACIÓN VIRTUAL","Educación","Educación","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE SECCIÓN DE GESTIÓN DE COBROS","Administración, Asistencia Técnica y Actividades Afines","Contabilidad, Auditoria, Banca, Finanzas y Actividades Afines","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE SECCION DE HISTORIAL ACADEMICO DE ESTUDIANTES","Educación","Formación Profesional y Aprovechamiento de Recursos Humanos","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE SECCION DE INFOR. Y RELAC. PUBLICAS","Administración, Asistencia Técnica y Actividades Afines","Información, Divulgación y Relaciones Públicas","Técnico y Profesional","Profesional",""); 

-- ******************************************************************************************************
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE SECCION DE INGRESOS","Administración, Asistencia Técnica y Actividades Afines","Contabilidad, Auditoria, Banca, Finanzas y Actividades Afines","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE SECCIÓN DE MANTENIMIENTO VEHÍCULAR","Telecomunicaciones, Correos, Transporte y Actividades Afines","Transporte y Actividades Afines","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE SECCIÓN DE OPERACIONES DE SEGURIDAD","Servicios Legales, Seguridad Pública y Actividades Afines","Seguridad Pública","Técnico y Profesional ","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE SECCIÓN DE ORNATO Y ASEO","Mantenimiento, Construcción, Mecánica, Artesanía, Artes Gráficas y Oficios Diversos","Oficios Diversos","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE SECCION DE PAGOS","Administración, Asistencia Técnica y Actividades Afines","Contabilidad, Auditoria, Banca, Finanzas y Actividades Afines","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE SECCION DE PLANILLAS","Administración, Asistencia Técnica y Actividades Afines","Contabilidad, Auditoria, Banca, Finanzas y Actividades Afines","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE SECCIÓN DE PRODUCCIÓN AUDIOVISUAL","Administración, Asistencia Técnica y Actividades Afines","Información, Divulgación y Relaciones Públicas","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE SECCION DE PRODUCCION GRAFICA","Mantenimiento, Construcción, Mecánica, Artesanía, Artes Gráficas y Oficios Diversos","Artes Gráficas","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE SECCIÓN DE PROTECCIÓN Y SEGURIDAD UNIVERSITARIA","Servicios Legales, Seguridad Pública y Actividades Afines","Seguridad Pública","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE SECCIÓN DE PUBLICIDAD Y MERCADEO","Administración, Asistencia Técnica y Actividades Afines","Estadística, Economía, Mercadeo, Turismo, Actuarial y Actividades Afines","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE SECCIÓN DE REVISIÓN FINAL DE CRÉDITOS","Administración, Asistencia Técnica y Actividades Afines","Información, Divulgación y Relaciones Públicas","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE SECCIÓN DE SEGUIMIENTO Y CONTROL","Administración, Asistencia Técnica y Actividades Afines","Información, Divulgación y Relaciones Públicas","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE SECCION DE SEGUIMIENTO Y CONTROL DE REGI. CONTABLES","Administración, Asistencia Técnica y Actividades Afines","Contabilidad, Auditoria, Banca, Finanzas y Actividades Afines","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE SECCIÓN DE SERVICIOS ADMINISTRATIVOS","Mantenimiento, Construcción, Mecánica, Artesanía, Artes Gráficas y Oficios Diversos","Oficios Diversos","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE SECCIÓN DE TRAMITACIÓN DE DOC. Y SERV. AL PÚBLICO","Administración, Asistencia Técnica y Actividades Afines","Información, Divulgación y Relaciones Públicas","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE SECCIÓN DE TRANSPORTE DE PERS., VAL. Y CONT. DE COMB","Telecomunicaciones, Correos, Transporte y Actividades Afines","Transporte y Actividades Afines","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE SECCIÓN DE VENTAS Y SERVICIOS","Salud Pública y Actividades Afines","Nutrición, Dietética y Servicio de Alimentos","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("JEFE DE SECCIÓN DE VIDEOVILANCIA E INVESTIGACIÓN DEL DELITO","Servicios Legales, Seguridad Pública y Actividades Afines","Seguridad Pública","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("LUMINOTÉCNICO","Administración, Asistencia Técnica y Actividades Afines","Información, Divulgación y Relaciones Públicas","Apoyo, Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("MECANICO AUTOMOTRIZ","Mantenimiento, Construcción, Mecánica, Artesanía, Artes Gráficas y Oficios Diversos","Mecánico Automotriz, de Aviación, Operación de Equipo Pesado y Actividades Afines","Apoyo, Auxiliar y Asistencial","Auxiliar",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("MECANICO DE REFRIGERACION","Mantenimiento, Construcción, Mecánica, Artesanía, Artes Gráficas y Oficios Diversos","Mecánica en General","Apoyo, Auxiliar y Asistencial","Auxiliar",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("MECANICO ELECTRONICO","Mantenimiento, Construcción, Mecánica, Artesanía, Artes Gráficas y Oficios Diversos","Mecánica en General","Apoyo, Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("MEDICO GENERAL","Salud Pública y Actividades Afines","Medicina, Odontología y Afines","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("MENSAJERO","Administración, Asistencia Técnica y Actividades Afines","Secretariado, Operación de Equipo de Oficina, Traducción y Actividades Afines","Apoyo, Auxiliar y Asistencial","Apoyo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("MUSICO","Educación","Bellas Artes, Cultura y Actividades Afines","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("MUSICO FOLKLORISTA","Educación","Bellas Artes, Cultura y Actividades Afines","Apoyo, Auxiliar y Asistencial","Auxiliar",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("OFICIAL CENTRAL DE REGISTROS DOCENTES","Educación","Educación","Apoyo, Auxiliar y Asistencial","Auxiliar",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("OFICIAL DE ASISTENCIA","Administración, Asistencia Técnica y Actividades Afines","Planificación, Análisis Administrativo, Personal y Presupuesto","Apoyo, Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("OFICIAL DE ASISTENCIA DOCENTE","Educación","Educación","Apoyo, Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("OFICIAL DE BIENES PATRIMONIALES","Administración, Asistencia Técnica y Actividades Afines","Contabilidad, Auditoria, Banca, Finanzas y Actividades Afines","Apoyo, Auxiliar y Asistencial","Auxiliar",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("OFICIAL DE COMPRAS","Administración, Asistencia Técnica y Actividades Afines","Ventas, Compras y Almacenamiento","Apoyo, Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("OFICIAL DE CONTABILIDAD","Administración, Asistencia Técnica y Actividades Afines","Contabilidad, Auditoria, Banca, Finanzas y Actividades Afines","Apoyo, Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("OFICIAL DE CONTROL DE SUMINISTROS","Administración, Asistencia Técnica y Actividades Afines","Ventas, Compras y Almacenamiento","Apoyo, Auxiliar y Asistencial","Apoyo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("OFICIAL DE DESCUENTOS","Administración, Asistencia Técnica y Actividades Afines","Contabilidad, Auditoria, Banca, Finanzas y Actividades Afines","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("OFICIAL DE ORGANIZACION DE EVENTOS","Administración, Asistencia Técnica y Actividades Afines","Información, Divulgación y Relaciones Públicas","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("OFICIAL DE PERSONAL","Administración, Asistencia Técnica y Actividades Afines","Planificación, Análisis Administrativo, Personal y Presupuesto","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("OFICIAL DE PLANILLAS","Administración, Asistencia Técnica y Actividades Afines","Contabilidad, Auditoria, Banca, Finanzas y Actividades Afines","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("OFICIAL DE PROTOCOLO","Administración, Asistencia Técnica y Actividades Afines","Información, Divulgación y Relaciones Públicas","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("OFICIAL DE REGISTRO Y CONTROL DE PAGOS","Administración, Asistencia Técnica y Actividades Afines","Tributación, Fiscalización y Control de Fondos Públicos","Apoyo, Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("OFICIAL DE REGISTROS DOCENTES","Educación","Educación","Apoyo, Auxiliar y Asistencial","Auxiliar",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("OFICIAL DE SEGURIDAD INFORMATICA","Administración, Asistencia Técnica y Actividades Afines","Procesamiento Electrónico de Datos","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("OFICIAL DE VENTAS","Administración, Asistencia Técnica y Actividades Afines","Ventas, Compras y Almacenamiento","Apoyo, Auxiliar y Asistencial","Auxiliar",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("OFICINISTA","Administración, Asistencia Técnica y Actividades Afines","Secretariado, Operación de Equipo de Oficina, Traducción y Actividades Afines","Apoyo, Auxiliar y Asistencial","Apoyo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("OFICINISTA AUXILIAR","Administración, Asistencia Técnica y Actividades Afines","Secretariado, Operación de Equipo de Oficina, Traducción y Actividades Afines","Apoyo, Auxiliar y Asistencial","Apoyo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("OFICINISTA DE COBROS","Administración, Asistencia Técnica y Actividades Afines","Tributación, Fiscalización y Control de Fondos Públicos","Apoyo, Auxiliar y Asistencial","Auxiliar",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("OPERADOR DE CENTRAL TELEFONICA","Telecomunicaciones, Correos, Transporte y Actividades Afines","Servicios de Comunicación","Apoyo, Auxiliar y Asistencial","Apoyo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("OPERADOR DEL CENTRO DE VIDEOVIGILANCIA","Servicios Legales, Seguridad Pública y Actividades Afines","Seguridad Pública","Apoyo, Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("OPERADOR DE COMPUTADORA","Administración, Asistencia Técnica y Actividades Afines","Procesamiento Electrónico de Datos","Apoyo, Auxiliar y Asistencial","Apoyo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("OPERADOR DE EQUIPO AUDIOVISUAL","Administración, Asistencia Técnica y Actividades Afines","Información, Divulgación y Relaciones Públicas","Apoyo, Auxiliar y Asistencial","Auxiliar",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("OPERADOR DE MAQUINA REPRODUCTORA","Administración, Asistencia Técnica y Actividades Afines","Secretariado, Operación de Equipo de Oficina, Traducción y Actividades Afines","Apoyo, Auxiliar y Asistencial","Apoyo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("OPERADOR DE PRENSA","Mantenimiento, Construcción, Mecánica, Artesanía, Artes Gráficas y Oficios Diversos","Artes Gráficas","Apoyo, Auxiliar y Asistencial","Auxiliar",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("OPERADOR DE RETROEXCAVADORA","Telecomunicaciones, Correos, Transporte y Actividades Afines","Transporte y Actividades Afines","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("PERFORADOR DE POZOS","Arquitectura, Ingeniería, Geodesia, Geografía y Actividades Afines","Ingeniería Sanitaria y Afines","Apoyo, Auxiliar y Asistencial","Auxiliar",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("PERIODISTA","Administración, Asistencia Técnica y Actividades Afines","Información, Divulgación y Relaciones Públicas","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("PINTOR","Mantenimiento, Construcción, Mecánica, Artesanía, Artes Gráficas y Oficios Diversos","Mantenimiento y Construcción","Apoyo, Auxiliar y Asistencial","Apoyo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("PLANIFICADOR","Administración, Asistencia Técnica y Actividades Afines","Planificación, Análisis Administrativo, Personal y Presupuesto","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("PRODUCTOR","Administración, Asistencia Técnica y Actividades Afines","Información, Divulgación y Relaciones Públicas","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("PROGRAMADOR DE COMPUTADORA","Administración, Asistencia Técnica y Actividades Afines","Procesamiento Electrónico de Datos","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("PROGRAMADOR WEB","Administración, Asistencia Técnica y Actividades Afines","Procesamiento Electrónico de Datos","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("PROMOTOR DE LA OFERTA ACADEMICA DEL SIU","Administración, Asistencia Técnica y Actividades Afines","Información, Divulgación y Relaciones Públicas","Apoyo, Auxiliar y Asistencial","Auxiliar",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("PSICOLOGO","Salud Pública y Actividades Afines","Medicina, Odontología y Afines","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("QUIMICO","Arquitectura, Ingeniería, Geodesia, Geografía y Actividades Afines","Ingeniería Industrial, Química y de Minas","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("RECEPCIONISTA","Telecomunicaciones, Correos, Transporte y Actividades Afines","Servicios de Comunicación","Apoyo, Auxiliar y Asistencial","Apoyo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("RELACIONISTA PUBLICO","Administración, Asistencia Técnica y Actividades Afines","Información, Divulgación y Relaciones Públicas","Apoyo, Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("SECRETARIA","Administración, Asistencia Técnica y Actividades Afines","Secretariado, Operación de Equipo de Oficina, Traducción y Actividades Afines","Apoyo, Auxiliar y Asistencial","Auxiliar",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("SECRETARIA EJECUTIVA","Administración, Asistencia Técnica y Actividades Afines","Secretariado, Operación de Equipo de Oficina, Traducción y Actividades Afines","Apoyo, Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("SECRETARIA PARLAMENTARIA","Administración, Asistencia Técnica y Actividades Afines","Secretariado, Operación de Equipo de Oficina, Traducción y Actividades Afines","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("SECRETARIA PARLAMENTARIA BILINGUE","Administración, Asistencia Técnica y Actividades Afines","Secretariado, Operación de Equipo de Oficina, Traducción y Actividades Afines","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("SECRETARIO ACADEMICO","Educación","Programación, Orientación, Inspección y Dirección de Actividades Educativas","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("SECRETARIO ADMINISTRATIVO","Educación","Programación, Orientación, Inspección y Dirección de Actividades Educativas","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("SOLDADOR","Mantenimiento, Construcción, Mecánica, Artesanía, Artes Gráficas y Oficios Diversos","Artesanía en General","Apoyo, Auxiliar y Asistencial","Apoyo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("SONIDISTA","Administración, Asistencia Técnica y Actividades Afines","Información, Divulgación y Relaciones Públicas","Apoyo, Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("SUB JEFE DEL DEPARTAMENTO DE TRANSPORTE","Telecomunicaciones, Correos, Transporte y Actividades Afines","Transporte y Actividades Afines","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("SUB-DIRECTOR ADMINISTRATIVO","Administración, Asistencia Técnica y Actividades Afines","Administración General","Técnico y Profesional","Jefes de Departamento",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("SUB-DIRECTOR DE BIENESTAR ESTUDIANTIL","Educación","Formación Profesional y Aprovechamiento de Recursos Humanos","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("SUB-DIRECTOR DE CARRERA UNIVERSITARIA","Administración, Asistencia Técnica y Actividades Afines","Planificación, Análisis Administrativo, Personal y Presupuesto","Ejecutivo","Directivo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("SUB-DIRECTOR DE EDITORIAL UNIVERSITARIA","Educación","Educación","Técnico y Profesional","Jefes de Departamento",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("SUB-DIRECTOR DE INFRAESTRUCTURA Y DESARROLLO FISICO","Arquitectura, Ingeniería, Geodesia, Geografía y Actividades Afines","Ingeniería Civil y Afines","Ejecutivo","Directivo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("SUB-DIRECTOR DE PERSONAL","Administración, Asistencia Técnica y Actividades Afines","Planificación, Análisis Administrativo, Personal y Presupuesto","Ejecutivo","Directivo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("SUB-DIRECTOR DE PLANIFICACIÓN UNIVERSITARIA","Administración, Asistencia Técnica y Actividades Afines","Planificación, Análisis Administrativo, Personal y Presupuesto","Ejecutivo","Directivo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("SUB-DIRECTOR DE PROVEEDURIA Y COMPRAS","Administración, Asistencia Técnica y Actividades Afines","Ventas, Compras y Almacenamiento","Técnico y Profesional","Jefes de Departamento",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("SUB-DIRECTOR DE PROYECTOS","Arquitectura, Ingeniería, Geodesia, Geografía y Actividades Afines","Ingeniería Civil y Afines","Ejecutivo","Directivo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("SUB DIRECTOR DE TECNOLOGIA DE LA INFORMACION Y COMUNICACION","Administración, Asistencia Técnica y Actividades Afines","Procesamiento Electrónico de Datos","Ejecutivo","Directivo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("SUB-JEFE DE DEPARTAMENTO DE CAFETERÍA","Salud Pública y Actividades Afines","Nutrición, Dietética y Servicio de Alimentos","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("SUB-JEFE DE DEPARTAMENTO DE SEGURIDAD INSTITUCIONAL","Servicios Legales, Seguridad Pública y Actividades Afines","Seguridad Pública","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("SUB-JEFE DE DEPARTAMENTO DE SERVICIOS ADM. GENERALES","Mantenimiento, Construcción, Mecánica, Artesanía, Artes Gráficas y Oficios Diversos","Artesanía en General","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("SUPERVISOR DE ANALISTA DE PRESUPUESTO","Administración, Asistencia Técnica y Actividades Afines","Planificación, Análisis Administrativo, Personal y Presupuesto","Técnico y Profesional","Profesional",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("SUPERVISOR DE AREAS VERDES","Ciencias Agropecuarias, Naturales y Actividades Afines","Ciencias Agropecuarias","Apoyo, Auxiliar y Asistencial","Auxiliar",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("SUPERVISOR DE ASEO","Mantenimiento, Construcción, Mecánica, Artesanía, Artes Gráficas y Oficios Diversos","Mantenimiento y Construcción","Apoyo, Auxiliar y Asistencial","Auxiliar",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("SUPERVISOR DE ASEO URBANO","Mantenimiento, Construcción, Mecánica, Artesanía, Artes Gráficas y Oficios Diversos","Oficios Diversos","Apoyo, Auxiliar y Asistencial","Auxiliar",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("SUPERVISOR DE BODEGA","Administración, Asistencia Técnica y Actividades Afines","Ventas, Compras y Almacenamiento","Apoyo, Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("SUPERVISOR DE CAFETERIA","Salud Pública y Actividades Afines","Nutrición, Dietética y Servicio de Alimentos","Apoyo, Auxiliar y Asistencial","Auxiliar",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("SUPERVISOR DE CARPINTERO","Mantenimiento, Construcción, Mecánica, Artesanía, Artes Gráficas y Oficios Diversos","Artesanía en General","Apoyo, Auxiliar y Asistencial","Auxiliar",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("SUPERVISOR DEL CENTRO DE VIDEOVIGILANCIA","Servicios Legales, Seguridad Pública y Actividades Afines","Seguridad Pública","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("SUPERVISOR DE EBANISTA","Mantenimiento, Construcción, Mecánica, Artesanía, Artes Gráficas y Oficios Diversos","Artesanía en General","Apoyo, Auxiliar y Asistencia","Auxiliar",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("SUPERVISOR DE EQUIPOS Y TALLERES","Mantenimiento, Construcción, Mecánica, Artesanía, Artes Gráficas y Oficios Diversos","Mecánica en General","Apoyo, Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("SUPERVISOR DE LABORATORIO","Arquitectura, Ingeniería, Geodesia, Geografía y Actividades Afines","Ingeniería Eléctrica y Electromecánica","Apoyo, Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("SUPERVISOR DE MANTENIMIENTO","Mantenimiento, Construcción, Mecánica, Artesanía, Artes Gráficas y Oficios Diversos","Mantenimiento y Construcción","Apoyo, Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("SUPERVISOR DE MECANICA","Mantenimiento, Construcción, Mecánica, Artesanía, Artes Gráficas y Oficios Diversos","Mecánica en General","Apoyo, Auxiliar y Asistencial","Auxiliar",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("SUPERVISOR DE ORGANIZACIÓN DE EVENTOS","Administración, Asistencia Técnica y Actividades Afines","Información, Divulgación y Relaciones Públicas","Apoyo, Auxiliar y Asistencial","Auxiliar",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("SUPERVISOR DE SERVICIOS ADMINISTRATIVOS","Mantenimiento, Construcción, Mecánica, Artesanía, Artes Gráficas y Oficios Diversos","Oficios Diversos","Apoyo, Auxiliar y Asistencial","Auxiliar",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("TECNICO ADMINISTRATIVO","Administración, Asistencia Técnica y Actividades Afines","Administración General","Apoyo, Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("TECNICO EN EDIFICACIONES","Arquitectura, Ingeniería, Geodesia, Geografía y Actividades Afines","Ingeniería Civil y Afines","Apoyo, Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("TECNICO EN INGENIERIA","Arquitectura, Ingeniería, Geodesia, Geografía y Actividades Afines","Ingeniería Civil y Afines","Apoyo, Auxiliar y Asistencial","Asistencial",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("TECNICO EN RECURSOS DE INFORMATICA","Administración, Asistencia Técnica y Actividades Afines","Procesamiento Electrónico de Datos","Apoyo, Auxiliar y Asistencial","Auxiliar",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("TECNICO EN SOPORTE DE EQUIPOS INFORMATICOS","Administración, Asistencia Técnica y Actividades Afines","Procesamiento Electrónico de Datos","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("TECNICO METROLOGO","Mantenimiento, Construcción, Mecánica, Artesanía, Artes Gráficas y Oficios Diversos","Mecánica en General","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("TRABAJADOR DE ASEO URBANO","Mantenimiento, Construcción, Mecánica, Artesanía, Artes Gráficas y Oficios Diversos","Oficios Diversos","Apoyo, Auxiliar y Asistencial","Apoyo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("TRABAJADOR MANUAL","Mantenimiento, Construcción, Mecánica, Artesanía, Artes Gráficas y Oficios Diversos","Oficios Diversos","Apoyo, Auxiliar y Asistencial","Apoyo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("TRABAJADOR MANUAL DE CAFETERIA","Mantenimiento, Construcción, Mecánica, Artesanía, Artes Gráficas y Oficios Diversos","Oficios Diversos","Apoyo, Auxiliar y Asistencial","Apoyo",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("TRABAJADOR SOCIAL","Trabajo, Bienestar Social y Actividades Afines","Bienestar Social y Afines","Técnico y Profesional","Técnico",""); 
INSERT INTO Cargos (Nombre, Familia, Grupo_ocupacional, Nivel_funcional, Grupo_laboral, PDF) VALUES ("TRAMOYISTA","Administración, Asistencia Técnica y Actividades Afines","Información, Divulgación y Relaciones Públicas","Apoyo, Auxiliar y Asistencial","Auxiliar",""); 

-- ******************************************************************************************************
-- SELECT * FROM Cargos;